### ISSUE TITLE
Escrever e revisar os documentos de elicitação

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Simplenote#10]
## Descrição
Escrever e revisar os documentos de elicitação

## Tarefas
- [x] Personas
- [x] Storytelling
- [x] Questionário
- [x] Introspecção
- [x] Glossário
- [x] Entrevista
- [x] BrainStorming

## Critérios de aceitação
Documentos criados e revisados

**Comment by Mylena-angelica** [comment]
Questionário pronto e disponível para revisão. 
@kaua-pt Enviei o link no grupo do whatsapp devido ao acesso para editar

**Comment by Mylena-angelica** [comment]
O questionário do novo aplicativo já está esperando a revisão. O link continua o mesmo

**Comment by Mylena-angelica** [comment]
Questionário foi elaborada e liberado. Obtivemos 23 respostas. Então a partir de hoje, vou elaborar a análise de dados e o questionário está fechado.

**Comment by Mylena-angelica** [comment]
Storytelling e glossário estão na issue [21-glossário-e-storytelling](https://github.com/Requisitos-de-Software/2023.1-Simplenote/tree/21-gloss%C3%A1rio-e-storytelling)
Introspecção na issue  [18-introspecção](https://github.com/Requisitos-de-Software/2023.1-Simplenote/pull/19)

**Comment by Mylena-angelica** [comment]
Todos os documentos de elicitação foram criados
