### ISSUE TITLE
Ajuste texto Aplicativo Selecionado

### ISSUE THREAD

**Issue by Beatrizvn** [Requisitos-de-Software/2023.1-Simplenote#14]
## Descrição
Com a mudança de app vamos alterar o texto do aplicativo selecionado
## Tarefas

- [x] Ajustar o texto

**Comment by Beatrizvn** [comment]
@ian-dcg o pull request foi feito, você precisa revisar o texto e aprova-lo

**Comment by Mylena-angelica** [comment]
@Beatrizvn @ian-dcg Adicionaram o termo de uso? Mostrando que a gente pode utilizar esse aplicativo para a disciplina?
O prof tinha dito que podia ser um print da página de termo de uso deles

**Comment by Beatrizvn** [comment]
Vou colocar o link na Bibliografia @Mylena-angelica

**Comment by Beatrizvn** [comment]
> 

Coloquei o Ian ainda precisa revisar
