### ISSUE TITLE
MoScoW

### ISSUE THREAD

**Issue by Beatrizvn** [Requisitos-de-Software/2023.1-Simplenote#20]
## Descrição
O método de priorização de MoSCoW é uma técnica utilizada em gerenciamento de projetos para classificar os requisitos do projeto em ordem de prioridade. MoSCoW é um acrônimo que significa Must have (Deve ter), Should have (Deveria ter), Could have (Poderia ter) e Won't have (Não terá).

## Tarefas

- [x] Deve ter
- [x] Deveria ter
- [x] Poderia ter
- [x] Não terá

## Informações adicionais
- Autor(es): Beatriz, Ana Beatriz
- Revisor(es): Mylena

**Comment by ananorberto** [comment]
Requisitos finalizados, prontos para pull request e revisão. 
@Beatrizvn 
@Mylena-angelica

**Comment by Mylena-angelica** [comment]
Revisão em andamento

**Comment by Mylena-angelica** [comment]
Criei a parte elicitação na tabela, para incluir qual método foi utilizado para checar àquele requisito
