### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by ian-dcg** [Requisitos-de-Software/2023.1-Simplenote#24]
## Descrição
O objetivo desta tarefa é elaborar as Personas e o Perfil de usuário do sistema.

## Tarefas
Criar o documento de Personas

## Critérios de aceitação
O perfil de usuário deve estar em conformidade com o questionário realizado pela equipe

## Informações adicionais
- Autor(es): Ian
- Revisor(es): Mylena

**Comment by ian-dcg** [comment]
O documento das Personas já está pronto. Aguardo a revisão @Mylena-angelica

**Comment by Mylena-angelica** [comment]
Revisão feita e PR aceito
