### ISSUE TITLE
Cenários

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Simplenote#39]
## Descrição
Criar o documento de cenários, tomando como base as técnicas de priorização

## Tarefas
- [x] Modelo de cenário
- [ ] Cenários identificados

## Informações adicionais
- Autor(es): Mylena e Leonardo
- Revisor(es): Kauã

**Comment by Mylena-angelica** [comment]
Início da criação do documento

**Comment by Mylena-angelica** [comment]
Para a criação e análise dos cenários, foi criado um arquivo na parte de priorização, com os requisitos com maior prioridades, escolhidos por meio das 3 técnicas de priorização.

**Comment by Mylena-angelica** [comment]
Os cenários criados terão como base os requisitos funcionais presentes no [documento ](https://github.com/Requisitos-de-Software/2023.1-Simplenote/blob/main/docs/elicitacao/Prioriza%C3%A7%C3%A3o/priorizacao_final.md)

**Comment by Mylena-angelica** [comment]
A principio serão ao todo 14 cenários:

- C01: Fazer anotação
- C02: Excluir anotação 
- C03: Visualizar anotações 
- C04: Criar nova nota com título e conteúdo 
- C05: Editar título e conteúdo de nota existente 
- C06: O usuário poderia separar suas notas em pastas 
- C07: O usuário deve poder usar Markdown
- C08: O usuário deve poder buscar notas por palavras-chave
- C09 :O usuário deve poder criar uma conta e fazer login
- C10 :O usuário deveria poder recuperar anotação excluída
- C11 :O usuário deve ser capaz de anexar imagens 
- C12 : O usuário deveria poder pesquisar por suas anotações
- C013 :O usuário deveria poder compartilhar notas com outras pessoas 
- C014 :O aplicativo deve permitir a adição de etiquetas nas notas para facilitar a organização

**Comment by Mylena-angelica** [comment]
Modelo de cenário criado

**Comment by Mylena-angelica** [comment]
Cenários de 1 a 6 criados

**Comment by kaua-pt** [comment]
Revisão dos cenários 1 a 6 efetuada!
