### ISSUE TITLE
Léxico

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Simplenote#40]
## Descrição
Criar documento de léxicos.

## Tarefas
- [x] Modelo dos léxicos
- [x] Léxicos

## Informações adicionais
- Autor(es): Beatriz e João
- Revisor(es): Ana

**Comment by ananorberto** [comment]
Documento realizado na branch #39.
O documento foi revisado, em bom estado e sem sugestão de melhoria/alteração.
Na gitpage também está correto e não apresenta nenhum erro de formatação e/ou gramática.
