### ISSUE TITLE
Entrega 3

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Simplenote#43]
## Descrição
Checklist da entrega 3

## Tarefas
- [x] Cenários
- [x] Léxicos
- [x] Casos de uso
- [x] Especificação suplementar
- [x] Ajustes do feedback
- [x] Vídeo
- [x] Conferência de documentação
- [x] Adicionar entrega 3 na páginas entrega
- [x] Gitpage
- [x] Release
- [x] Envio do link para o professor

**Comment by Mylena-angelica** [comment]
# Pontos da entrega 3 presente no plano de ensino:
### Entrega 3: Modelagem de Requisitos (Cenários , Léxico, Use Case, Especificação Suplementar)

- [ ] O histórico de versão padronizado?
- [ ] O(s) autor(es) e o(s) revisor(es) para cada artefato?
- [ ] O vídeo de apresentação na categoria “não listado” no youtube?
- [ ] As referências bibliográficas e/ou bibliografia em todos os artefatos;
- [ ] As tabelas e/ou imagens possuem legenda e fonte e elas chamadas dentro dos texto?
- [ ] Um texto fazendo uma introdução dos artefatos?
- [ ] O cronograma executado com quem realizou cada artefato/atividade com as datas de início e fim
da construção/realização do artefato/atividade.
- [ ]   A(s) ata(s) da(s) reuniões (com data, horário de início e do final, participantes, objetivo, atividades
definidas etc).
- [ ] As especificações dos cenários para o projeto
- [ ] Os cenários possuem os elementos básicos de um cenário (Título, Metas/Objetivo, Contexto,
Atores, Recursos, Exceção e Episódios)
- [ ] As especificações dos Léxicos?
- [ ] A definição do usuário nos Léxicos?
- [ ] Os léxicos possuem ligações entre si
- [ ] Os léxicos utilizam a estrutura de dicionário (verbo, objeto, estado)?
- [ ] A especificação dos caso de uso?
- [ ] Os atores principais e atores secundários no diagrama de caso de uso?
- [ ]  O ator principal está do lado esquerdo do sistema no diagrama de caso de uso?
- [ ] Os atores estão fora da caixa de limite do sistema no diagrama de caso de uso?
- [ ] A especificação do diagrama de caso de uso (com Nome, Descrição, Atores, Pré-Condição,PósCondição, Fluxo Principal, Fluxo Alternativo e Fluxo de Exceção etc.)?
- [ ] A participação do cliente e/ou persona na validação do Diagrama de Casa de Uso?
- [ ] A especificação suplementar?
- [ ] O artefato segue o modelo FURPS+?
- [ ] O documento especifica o tempo de resposta, no Desempenho?
- [ ] O documento especifica qual plataforma o aplicativo pode ser executado?
- [ ] Todos os requisitos podem ser testados (RF e RNF)?
