### ISSUE TITLE
Histórias de Usuário

### ISSUE THREAD

**Issue by Mylena-angelica** [Requisitos-de-Software/2023.1-Simplenote#46]
## Descrição

Elaboração do documento de histórias de usuário

## Tarefas

- [x] Criar documentação
- [x] Padronizar versão (introdução, bibliografia, introdução, títulos e fonte de imagens e tabelas, histórico de versão)
- [x] Os títulos das histórias de usuário são auto-explicativo
- [x] O “quem”, “o que” e o “por que” estão definidos na descrição da história de usuário
- [x] A participação do cliente e/ou persona na validação das histórias de usuário
- [x] A história possui critérios de aceitação
- [x] Os critérios de aceitação das histórias foram definidos
- [x] Todas as histórias de usuários podem ser testadas

## Critérios de aceitação

Documento elaborado e revisado
## Informações adicionais

- Autor(es): Kauã e João
- Revisor(es): Mylena

**Comment by kaua-pt** [comment]
Documento inicializado
