### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by Mylena-angelica** [Requisitos-de-Software/2023.1-Simplenote#48]
## Descrição
Elaborar a documentação do backlog

## Tarefas

- [x] Criar documentação
- [x] Padronizar versão (introdução, bibliografia, introdução, títulos e fonte de imagens e tabelas, histórico de versão)
- [x] O backlog possui épicos e temas bem definidos e descritos
- [x] As Histórias de Usuário seguem algum modelo ou padrão

## Critérios de aceitação

Documentação criada e revisada
## Informações adicionais

- Autor(es): Ana e Ian
- Revisor(es): João

**Comment by ananorberto** [comment]
## Documento em ajustes finais.
### Já finalizado:

- [ ] Introdução
- [ ] Metodologia
- [ ] Tabela de Requisitos funcionais
- [ ] Épicos de 01 á 08
- [ ] Criação da tabela e adição dos épicos

### Falta finalizar: 

@ian-dcg 
- [ ] Adicionar épicos 9 á 12
- [ ] Adicionar na tabela
- [ ] Adicionar ID, Prioridade e Origem do épico
