### ISSUE TITLE
Ajuste de Feedbacks entrega 2

### ISSUE THREAD

**Issue by Mylena-angelica** [Requisitos-de-Software/2023.1-Simplenote#49]
## Descrição
Fazer os ajustes indicados pelo professor e pela monitora no feedback da entrega 2

## Tarefas

- [x] Fazer os ajustes

## Critérios de aceitação

Ajustes feitos e revisados

## Informações adicionais
- Autor(es): Ana e Beatriz
- Revisor(es): Mylena

**Comment by ananorberto** [comment]
## Ajustes finalizados

- [ ]  Onde foi distribuído o Questionário (4)
- [ ] Tarefas primárias (5)
- [ ] Quantidade de personas (11)
- [ ] Mediador Brainstorm (14)
- [ ] Dados demográficos dos entrevistados (15)
- [ ] Encenação Storytelling (16)
- [ ] Cronograma da priorização (18)
- [ ] Participação do usuário FTF (19)

> Os ajustes que restaram são referentes as gravações das reuniões.
