### ISSUE TITLE
Validação da documentação do projeto

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Simplenote#61]
## Descrição
Realizar a validação dos artefatos enviando um email para o simplenote.

## Tarefas
- [x] Enviar email
- [x] Protótipo

## Critérios de aceitação

- Apenas enviar o email, não é totalmente necessário uma resposta;
- Protótipo com requisitos que não estão presentes no app.

## Informações adicionais
- Autor(es): Mylena e Ana
- Revisor(es): João

**Comment by Mylena-angelica** [comment]
O protótipo está sendo elaborado no [figma](https://www.figma.com/file/SJaUsv3icFSlu8DxhEPdZg/SimpleNote?type=design&node-id=0%3A1&t=46U7qe47kCO6yXqF-1)

**Comment by Mylena-angelica** [comment]
O que será aficionado na versão prototipada é a inclusão de requisitos que foram elicitados no trabalho mas não estão incorporados no aplicativo e que possuem uma boa classificação na fase de priorização. Foram considerados somente requisitos funcionais para essa prototipação 

- [ ] Criar checklists nas notas
- [ ] O aplicativo deve permitir a adição de etiquetas nas notas para facilitar a organização
- [ ] Possibilidade de usar marcação de texto (negrito, itálico, etc)
- [ ] O usuario poderia separar suas notas em pastas
- [ ] O usuario poderia definir templates para suas notas
- [ ] O usuario poderia importar ou exportar modelos de layout
- [ ] O aplicativo poderia ter integração com outros aplicativos
- [ ] O usuário poderia definir um lembrete para suas notas
- [ ] O sistema poderia fornecer estatísticas sobre as notas
- [ ] O sistema poderia oferecer sugestões de notas relacionadas
- [ ] O usúario deveria poder recuperar anotação excluida
- [ ] O usuário deveria poder definir cores para suas tags
- [ ] Para o primeiro acesso do usuário, deve ter uma breve explicação sobre o aplicativo e as suas funcionalidades
- [ ] O usuário poderia ver informações sobre sua nota
- [ ] Capacidade de criar no dispositivo um arquivo cópia de uma nota
- [ ] O aplicativo deve possuir um editor de texto avançado para permitir a utilização da função toggle
- [ ] Poder baixar uma cópia da nota no dispositivo
- [ ] O usuário deve ser capaz de pesquisar notas por palavra-chave ou tag.
- [ ] Os usuários devem poder exportar suas notas em diferentes formatos, como PDF ou Word, para uso posterior fora do aplicativo.
- [ ] O usuário deve ser capaz de anexar arquivos, imagens, áudios ou vídeos às notas.
- [ ] O aplicativo deve manter um histórico de versão de notas, permitindo que os usuários voltem para versões anteriores de suas notas.

**Comment by Mylena-angelica** [comment]
Para a prototipação serão feitas as seguintes telas

| Tela | Requisito | Pronta | 
|-----|------------|---------|
| Escrita de nota | 1|     |

1.Possibilidade de usar marcação de texto (negrito, itálico, etc)
2. O usuário poderia separar suas notas em pastas
3. O usuário poderia definir templates para suas notas
4. O usuário poderia importar ou exportar modelos de layout
5. O aplicativo poderia ter integração com outros aplicativos
6. O usuário poderia definir um lembrete para suas notas
7. O sistema poderia fornecer estatísticas sobre as notas
8. O sistema poderia oferecer sugestões de notas relacionadas
9.O usuário deveria poder recuperar anotação excluída
10.  O usuário deveria poder definir cores para suas tags
11. Para o primeiro acesso do usuário, deve ter uma breve explicação sobre o aplicativo e as suas funcionalidades
12. Capacidade de criar no dispositivo um arquivo cópia de uma nota
13. O aplicativo deve possuir um editor de texto avançado para permitir a utilização da função toggle
14. Poder baixar uma cópia da nota no dispositivo
15 O usuário deve ser capaz de pesquisar notas por palavra-chave ou tag..pastas
16.Os usuários devem poder exportar suas notas em diferentes formatos, como PDF ou Word, para uso posterior fora do aplicativo.
17. O usuário deve ser capaz de anexar arquivos, imagens, áudios ou vídeos às notas.
18. O aplicativo deve manter um histórico de versão de notas, permitindo que os usuários voltem para versões anteriores de suas notas.

**Comment by Mylena-angelica** [comment]
1.Possibilidade de usar marcação de texto (negrito, itálico, etc), Essa é incorporada na parte de escrita em markdowm

**Comment by Mylena-angelica** [comment]
Prototipação finalizada, para acessar [clique aqui.](https://www.figma.com/proto/oAmOTvKcjLRS654uMoQSPN/SimpleNote?type=design&node-id=16-14&scaling=scale-down&page-id=0%3A1&starting-point-node-id=16%3A14).

@ananorberto @bot-do-jao Esperando revisão

**Comment by ananorberto** [comment]
Artefatos finalizados e prontos para revisão.
A Issue poderá ser fechada assim que o pull request #78 for aceito. #
