### ISSUE TITLE
Verificar documentação do grupo 6

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Simplenote#62]
## Descrição
Verificar documentação do grupo 6

## Tarefas
- Planejamento
   - [x] Aplicativo
   - [x] Cronograma
   - [x] Ferramentas
   - [x] RichPicture
   - [x] Metodologias

- Elicitação
   - [x] Analise
   - [x] Entrevista
   - [x] Introspecção
   - [x] Justificativa
   - [x] Perfil de Usuário
   - [x] Personas
   - [x] Priorização
   - [x] Requisitos Elicitados
   - [x] Storytelling
   - [x] Glossário
   - [x] Questionário
   - [x] Brainstorming
   - [x] Requisitos Elicitados
  
- Modelagem
   - [x] Casos de Uso
   - [x] Cenários
   - [x] Especificação Suplementar
   - [x] Léxicos
   - [x] NFR
   - [x] Backlog
   - [x] Histórias de Usuário
  
- Extras
   - [x] Ata
   - [x] Gitpage

**Comment by Mylena-angelica** [comment]
Foi decidido que cada um dos autores dos artefatos semelhantes ao do nosso grupo, serão os responsáveis por fazer a tabela de verificação do grupo 6. Os respectivos revisores irão revisar

**Comment by Mylena-angelica** [comment]
### Autores e revisores de casa artefato verificado

|Artefato| Responsáveis |
|--|--|
| Aplicativo | @Beatrizvn  @leonardogonmac @ian-dcg  |
| Cronograma | @Beatrizvn @kaua-pt @bot-do-jao  |  
| Ferramentas| @kaua-pt @bot-do-jao  |  
| RichPicture | @Beatrizvn @leonardogonmac @ian-dcg  |  
| Metodologias | @kaua-pt @bot-do-jao  |  
| Entrevista| @ananorberto @Beatrizvn  |  
| Introspecção | @Beatrizvn @leonardogonmac  |  
| Brainstorming|  @ian-dcg @ananorberto |  
| Glossário | @leonardogonmac @kaua-pt   |
| Questionário| @Mylena-angelica @kaua-pt |
| Storytelling | @leonardogonmac @ian-dcg |
| Personas |  @ian-dcg @Mylena-angelica |  
| Priorização | @Mylena-angelica @kaua-pt @bot-do-jao @Beatrizvn @ananorberto   |  
| Requisitos Elicitados | @Mylena-angelica @Beatrizvn  |  
| Casos de Uso | @Mylena-angelica @ian-dcg   |  
| Cenários | @Mylena-angelica @leonardogonmac @kaua-pt  |  
| Léxicos | @Beatrizvn @ananorberto @bot-do-jao  |  
|  NFR | @Beatrizvn @ananorberto @Mylena-angelica @leonardogonmac   |  
| Backlog| @ian-dcg @ananorberto @bot-do-jao  |  
| Histórias de Usuário | @kaua-pt @Mylena-angelica @bot-do-jao   |  
| Atas | @Mylena-angelica  |  
| Gitpage |  @ananorberto @Mylena-angelica |

**Comment by Mylena-angelica** [comment]
A planilha está sendo elaborada [nesse link](https://docs.google.com/spreadsheets/d/1buwmhsb6Lum_kM08czoQjU6hk08YbWzA1iZusyLgWVE/edit?usp=sharing)

**Comment by Mylena-angelica** [comment]
A parte da gitpage, atas,backlog,entrevista já foi feito

**Comment by Mylena-angelica** [comment]
As seguintes verificações estão conforme o novo template:

- Atas;
- Questionário;
- Requisitos elicitados (não possuem essa página no documento deles)

**Comment by Beatrizvn** [comment]
As seguintes verificações estão conforme o novo template:

Rich Picture;
NFR;
Introspecção.

**Comment by kaua-pt** [comment]
As seguintes verificações estão conforme o novo template: 

Cronograma;
Metodologia;
Priorização;
Especificação suplementar;
User stories;
