### ISSUE TITLE
Verificar documentação do nosso grupo

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Simplenote#63]
## Descrição
Verificar documentação do grupo 5

## Tarefas
- Planejamento
   - [x] Aplicativo
   - [x] Cronograma
   - [x] Ferramentas
   - [ ] Metodologia

- Pré-Rastreabilidade
   - [x] RichPicture

- Elicitação
   - [x] Instrospecção
   - [x] Brainstorming
   - [x] Entrevista
   - [x] Glossário
   - [x] Personas
   - [x] Questionário
   - [x] Storytelling

- Priorização
  - [x] FTF
  - [x] TLE
  - [x] Moscow

- Modelagem
   - [x] Casos de Uso
   - [x] Cenários
   - [x] Especificação Suplementar
   - [x] Léxicos
   - [x] NFR
   - [x] Backlog
   - [x] Histórias de Usuário

**Comment by Mylena-angelica** [comment]
Aguardando a finalização do checklist de verificação e a sua validação, que será feita na entrega 5.1

**Comment by Beatrizvn** [comment]
### Planejamento
Rich picture - Ian
App - João
Cronograma - Ian
Cronograma realizado - Ian
Ferramentas - Ian
Metodologias - Kauã

### Elicitação
Introspecção - João
Brainstorming - João
Entrevista - João
Glossário - João
Storytelling - Kauã
Questionário - Kauã
Personas - Kauã
FTF - Beatriz
TLE - Beatriz
Moscow - Kauã

### Modelagem
NFR - Leonardo
Léxicos - Leonardo
Cenários - Leonardo
Especificação Suplementar - Leonardo
Casos de Uso - Beatriz
Backlog - Beatriz
Histórias de usuário - Beatriz
