### ISSUE TITLE
Corrigir documentos do projeto com base na avaliação do grupo 4

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Simplenote#71]
## Descrição
Corrigir documentos do projeto com base na avaliação do grupo 4

## Tarefas
- Planejamento
   - [x] Rich picture
   - [x] App
   - [x] Cronograma
   - [x] Cronograma realizado
   - [x] Ferramentas
   - [x] Metodologias
- Elicitação
   - [x] Introspecção
   - [x] Brainstorming
   - [x] Entrevista
   - [x] Glossário
   - [x] Storytelling
   - [x] Questionário
   - [x] Personas
   - [x] FTF
   - [x] TLE
   - [x] Moscow
- Modelagem
   - [x] NFR
   - [x] Léxicos
   - [x] Cenários
   - [x] Especificação Suplementar
   - [x] Casos de Uso
   - [x] Backlog
   - [x] Histórias de usuário

**Comment by Beatrizvn** [comment]
### Planejamento
 Rich picture - Beatriz
 App - Ian
 Cronograma - Kauã
 Cronograma realizado - Kauã
 Ferramentas - Ian
 Metodologias - Kauã

### Elicitação
 Introspecção - João
 Brainstorming - Ian
 Entrevista - Ana Beatriz
 Glossário - Leonardo
 Storytelling - Leonardo
 Questionário - Beatriz
 Personas - Leonardo
 FTF - Kauã
 TLE - João
 Moscow - Ana Beatriz

### Modelagem

 NFR - Beatriz
 Léxicos - João
 Cenários - Beatriz
 Especificação Suplementar - Kauã
 Casos de Uso - João
 Backlog - Ana Beatriz
 Histórias de usuário - Kauã

**Comment by ananorberto** [comment]
Artefatos corrigidos:
- Entrevista.md
- Moscow.md
- Backlog.md

Prontos para revisão
