### ISSUE TITLE
Criar documento de Backward-from

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Simplenote#72]
## Descrição
Criar documento de Backward-from
## Tarefas
- [x] Requisitos Funcionais
- [x] Elos Funcionais
- [x] Requisitos Não Funcionais
- [x] Elos Não funcionais

## Informações adicionais
- Autor(es): João, Leonardo e Mylena
- Revisor(es): Ana, Beatriz e Kauã

**Comment by Mylena-angelica** [comment]
Documento criado e PR aceito. Merge ok
