### ISSUE TITLE
Criar documento de Forward-from

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Simplenote#73]
## Descrição
Criar documento de Forward-from
## Tarefas
- [x] Requisitos Funcionais
- [x] Requisitos Não Funcionais

## Informações adicionais
- Autor(es): Ana, Beatriz e Kauã
- Revisor(es): João, Leonardo e Mylena

**Comment by Mylena-angelica** [comment]
Documento criado e PR aceito. Merge ok
