### ISSUE TITLE
Entrega final

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Simplenote#84]
## Descrição
Entrega final do projeto
## Tarefas
- [x] Post Mortem
- [x] Correção dos documentos
- [x] Documentação final
- [x] Gravação da entrega
- [x] Gitpage
- [x] Entrega do link ao professor

**Comment by Mylena-angelica** [comment]
## To do list

- [ ] Terminar a página das entregas
- [ ] Merge no post mortem
- [ ] Concluir páginas entregas
- [ ] Ajustes StoryTelling
- [ ] Testar links verificação grupo 6
- [ ] Checar links de todos os artefatos
- [ ] Ajustes personas
- [ ] Ajustes priorização final
- [ ] Ajustes 3levelscale
- [ ] Ajustes introspeção
- [ ] Ajustes brainstorimg
- [ ] Ajustes glossário
- [ ] Ajustes casos de uso
- [ ] Ajustes aplicativo selecionado
- [ ] Ajustes ferramentas
- [ ] Ajustes aplicativos avaliadaos
- [ ]
