### ISSUE TITLE
Escrever e revisar os documentos de priorização

### ISSUE THREAD

**Issue by kaua-pt** [Requisitos-de-Software/2023.1-Simplenote#9]
## Descrição
Criar e revisar documentos de priorização

## Tarefas
- [ ] Frist Things Frist 
- [ ] Escala de três níveis
- [x] MoSCow

## Critérios de aceitação
Documentos criados e revisados

## Informações adicionais:

- Autores: Beatriz, Ana, Kauã e João
- Revisora: Mylena

**Comment by kaua-pt** [comment]
Documentos parcialmente escritos

**Comment by Mylena-angelica** [comment]
A priorização MoScoW está sendo feita na Issue MoScoW #20

**Comment by Mylena-angelica** [comment]
Revisão do MoScoW concluida

**Comment by Mylena-angelica** [comment]
Issues individuais abertas
